# Project information
site_name: Nebula Graph Manual
site_description: Documentation for Nebula Graph
site_author: Nebula Graph
site_url: https://docs.nebula-graph.io
edit_uri: ''

# repository
repo_name: 'vesoft-inc/nebula'
repo_url: 'https://github.com/vesoft-inc/nebula'

# Copyright
copyright: Copyright &copy; 2020 Nebula Graph

# Configuration
theme:
  name: 'material'
  logo:
    icon: library_books
  favicon: 'docs/img/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: false
  language: 'en'

# extra_css:
#     - 'theme/structor-menu.css'
#     - 'theme/extra.css'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/vesoft-inc/nebula'
    - type: 'weibo'
      link: 'https://www.weibo.com/u/7122684542?is_hot=1'
    - type: 'twitter'
      link: 'https://twitter.com/NebulaGraph'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/vesoft-nebula-graph/'
    - type: 'facebook'
      link: 'https://www.facebook.com/NebulaGraph/'
    - type: 'slack'
      link: 'https://app.slack.com/client/TJB3N2BPD/CJNFUM7AR'

nav:
    # - Version:
    #   - RC3 1.0.0: https://docs.nebula-graph.io/

    - Overview:
      - Introduction: manual-EN/0.about-this-manual.md
      - Concepts:
        - Data Model: manual-EN/1.overview/1.concepts/1.data-model.md
        - nGQL Overview: manual-EN/1.overview/1.concepts/2.nGQL-overview.md
      - Quick Start:
        - Get Started: manual-EN/1.overview/2.quick-start/1.get-started.md
        - FAQ: manual-EN/1.overview/2.quick-start/2.FAQ.md
        - Supported Clients: manual-EN/1.overview/2.quick-start/3.supported-clients.md
        - Build Source Code: manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
        - Deploy Cluster: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
        - Import .csv File: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/import-csv-file.md
        - Ingest .sst File: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md  
      - Design and Architecture:
        - Design and Architecture: manual-EN/1.overview/3.design-and-architecture/1.design-and-architecture.md
        - Storage Design: manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
        - Query Engine: manual-EN/1.overview/3.design-and-architecture/3.query-engine.md


    - Query Language:
      - Data Types:
        - Data Types: manual-EN/2.query-language/1.data-types/data-types.md
        - Type Conversion: manual-EN/2.query-language/1.data-types/type-conversion.md
      - Functions and Operators:
        - Bitwise Operators: manual-EN/2.query-language/2.functions-and-operators/bitwise-operators.md
        - Built in Functions: manual-EN/2.query-language/2.functions-and-operators/built-in-functions.md
        - Comparison Functions and Operators: manual-EN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
        - Aggregate GROUP BY Functions: manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
        - LIMIT Syntax: manual-EN/2.query-language/2.functions-and-operators/limit-syntax.md
        - Logical Operators: manual-EN/2.query-language/2.functions-and-operators/logical-operators.md
        - Operator Precedence: manual-EN/2.query-language/2.functions-and-operators/operator-precedence.md
        - ORDER BY Function: manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
        - Set Operations: manual-EN/2.query-language/2.functions-and-operators/set-operations.md
        - UUID Function: manual-EN/2.query-language/2.functions-and-operators/uuid.md
      - Language Structure:
        - Literal Values:
          - Boolean Literals: manual-EN/2.query-language/3.language-structure/literal-values/boolean-literals.md
          - Numeric Literals: manual-EN/2.query-language/3.language-structure/literal-values/numeric-literals.md
          - String Literals: manual-EN/2.query-language/3.language-structure/literal-values/string-literals.md

        - Comment Syntax: manual-EN/2.query-language/3.language-structure/comment-syntax.md
        - Identifer Case Sensitivity: manual-EN/2.query-language/3.language-structure/identifier-case-sensitivity.md
        - Keywords and Reserved Words: manual-EN/2.query-language/3.language-structure/keywords-and-reserved-words.md
        - Pipe Syntax: manual-EN/2.query-language/3.language-structure/pipe-syntax.md
        - Property Reference: manual-EN/2.query-language/3.language-structure/property-reference.md
        - Schema Object Names: manual-EN/2.query-language/3.language-structure/schema-object-names.md
        - Statement Composition: manual-EN/2.query-language/3.language-structure/statement-composition.md
        - User Defined Variables: manual-EN/2.query-language/3.language-structure/user-defined-variables.md
      - Statement Syntax:
        - Data Definition Statements:
            - ALTER TAG EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
            - CREATE SPACE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
            - CREATE TAG EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
            - DROP EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-edge-syntax.md
            - DROP SPACE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-space-syntax.md
            - DROP TAG Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
            - INDEX Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
            - TTL: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
        - Data Query and Manipulation Statements:
            - DELETE EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
            - DELETE VERTEX Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
            - FETCH Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
            - GO Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
            - INSERT EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
            - INSERT VERTEX Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
            - LOOK UP Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md
            - RETURN Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
            - UPDATE VERTEX EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
            - UPSERT Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/upsert-syntax.md
            - WHERE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
            - YIELD Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
        - Utility Statements:
            - DESCRIBE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
            - USE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
            - SHOW Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
        - Graph Algorithm:
            - FIND PATH Syntax: manual-EN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md

    - Build Develop and Administration:
      - Build:
        - Build Source Code: manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
        - Build by Docker: manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
      - Develop and Interface:
        - Kv Value API: manual-EN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
      - Deploy and Administration:
        - Deployment:
          - Configuration Description: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/configuration-description.md
          - Deploy Cluster on Docker: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster-on-docker.md
          - Deploy Cluster: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
          - Install With rpm Package: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/install-with-rpm-deb.md
        - Server Administration:
          - Account Management Statements:
            - CREATE USER Syntax: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/create-user-syntax.md
            - DROP USER Syntax: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/drop-user-syntax.md
            - GRANT ROLE Syntax: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/grant-role-syntax.md
            - REVOKE Syntax: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/revoke-syntax.md
          - Configuration Statements:
            - Configs Syntax: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
            - Log: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
            # - RocksDB Compaction and Flush: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
            - Logs: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
          - Graph Service Administration:
            - Graph Metrics: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/graph-service-administration/graph-metrics.md
          - Meta Service Administration:
            - Meta Metrics: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/meta-service-administration/meta-metrics.md
          - Storage Operation:
            - Data Export:
              - Dump Tool: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-export/dump-tool.md
            - Data Import:
              - Download and Ingest sst File: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md
              - Import csv File: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/import-csv-file.md
              - Spark Writer: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
            - Cluster Snapshot: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/cluster-snapshot.md
            - Storage Balance: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
            - Storage Metrics: manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md

    - Contributions:
      - Contribute to Documentation: manual-EN/4.contributions/contribute-to-documentation.md
      - cpp Coding Style: manual-EN/4.contributions/cpp-coding-style.md
      - Developer Documentation Style Guide: manual-EN/4.contributions/developer-documentation-style-guide.md
      - How to Contribute: manual-EN/4.contributions/how-to-contribute.md
    - Appendix:
      - Cypher & nGQL: manual-EN/5.appendix/cypher-ngql.md
      - Gremlin & nGQL: manual-EN/5.appendix/gremlin-ngql.md
      



# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      separator: "_"
# Plugins
plugins:
  - search





