# Project information
site_name: Nebula Graph Manual
site_description: Documentation for Nebula Graph
site_author: Nebula Graph
site_url: https://docs.nebula-graph.io
edit_uri: ''

# repository
repo_name: 'vesoft-inc/nebula'
repo_url: 'https://github.com/vesoft-inc/nebula'

# Copyright
copyright: Copyright &copy; 2020 Nebula Graph

# Configuration
theme:
  name: 'material'
  logo:
    icon: library_books
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
  language: 'en'

# extra_css:
#     - 'theme/structor-menu.css'
#     - 'theme/extra.css'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/vesoft-inc/nebula'
    - type: 'weibo'
      link: 'https://www.weibo.com/u/7122684542?is_hot=1'
    - type: 'twitter'
      link: 'https://twitter.com/NebulaGraph'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/vesoft-nebula-graph/'
    - type: 'facebook'
      link: 'https://www.facebook.com/NebulaGraph/'
    - type: 'slack'
      link: 'https://app.slack.com/client/TJB3N2BPD/CJNFUM7AR'

nav:
    # - Version: '../'

    - Overview:
      - Introduction: manual-EN/0.about-this-manual.md
      - Concepts:
        - Data Model: manual-EN/1.overview/1.concepts/1.data-model.md
        - nGQL Overview: manual-EN/1.overview/1.concepts/2.nGQL-overview.md
      - Quick Start:
        - Get Started: manual-EN/1.overview/2.quick-start/1.get-started.md
        - FAQ: manual-EN/1.overview/2.quick-start/2.FAQ.md
        - Supported Clients: manual-EN/1.overview/2.quick-start/3.supported-clients.md
        - Build Source Code: manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
        - Import .csv File: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-import/import-csv-file.md
        # - Ingest .sst File: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-import/download-and-ingest-sst-file.md
      - Design and Architecture:
        - Design and Architecture: manual-EN/1.overview/3.design-and-architecture/1.design-and-architecture.md
        - Storage Design: manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
        - Query Engine: manual-EN/1.overview/3.design-and-architecture/3.query-engine.md


    - Query Language:
      - Introduction: manual-EN/2.query-language/0.README.md
      - Data Types:
        - Data Types: manual-EN/2.query-language/1.data-types/data-types.md
        - Type Conversion: manual-EN/2.query-language/1.data-types/type-conversion.md
      - Functions and Operators:
        - Bitwise Operators: manual-EN/2.query-language/2.functions-and-operators/bitwise-operators.md
        - Built in Functions: manual-EN/2.query-language/2.functions-and-operators/built-in-functions.md
        - Comparison Functions and Operators: manual-EN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
        - Aggregate GROUP BY Functions: manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
        - LIMIT Syntax: manual-EN/2.query-language/2.functions-and-operators/limit-syntax.md
        - Logical Operators: manual-EN/2.query-language/2.functions-and-operators/logical-operators.md
        - Operator Precedence: manual-EN/2.query-language/2.functions-and-operators/operator-precedence.md
        - ORDER BY Function: manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
        - Set Operations: manual-EN/2.query-language/2.functions-and-operators/set-operations.md
        - String Comparison Functions and Operators: manual-EN/2.query-language/2.functions-and-operators/string-comparison-functions-and-operators.md
        - UUID Function: manual-EN/2.query-language/2.functions-and-operators/uuid.md
      - Language Structure:
        - Literal Values:
          - Boolean Literals: manual-EN/2.query-language/3.language-structure/literal-values/boolean-literals.md
          - Numeric Literals: manual-EN/2.query-language/3.language-structure/literal-values/numeric-literals.md
          - String Literals: manual-EN/2.query-language/3.language-structure/literal-values/string-literals.md

        - Comment Syntax: manual-EN/2.query-language/3.language-structure/comment-syntax.md
        - Identifer Case Sensitivity: manual-EN/2.query-language/3.language-structure/identifier-case-sensitivity.md
        - Keywords and Reserved Words: manual-EN/2.query-language/3.language-structure/keywords-and-reserved-words.md
        - Pipe Syntax: manual-EN/2.query-language/3.language-structure/pipe-syntax.md
        - Property Reference: manual-EN/2.query-language/3.language-structure/property-reference.md
        - Schema Object Names: manual-EN/2.query-language/3.language-structure/schema-object-names.md
        - Statement Composition: manual-EN/2.query-language/3.language-structure/statement-composition.md
        - User Defined Variables: manual-EN/2.query-language/3.language-structure/user-defined-variables.md
      - Statement Syntax:
        - Data Definition Statements:
            - ALTER TAG EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
            - CREATE SPACE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
            - CREATE TAG EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
            - DROP EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-edge-syntax.md
            - DROP SPACE Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-space-syntax.md
            - DROP TAG Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
            - INDEX Syntax: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
            - TTL: manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
        - Data Query and Manipulation Statements:
            - DELETE EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
            - DELETE VERTEX Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
            - FETCH Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
            - GO Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
            - INSERT EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
            - INSERT VERTEX Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
            - LOOK UP Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md
            - RETURN Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
            - UPDATE VERTEX EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
            - UPSERT Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/upsert-syntax.md
            - WHERE Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
            - YIELD Syntax: manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
        - Utility Statements:
            - SHOW Statements:
              - SHOW CHARSET Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-charset-syntax.md
              - SHOW COLLATION Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-collation-syntax.md
              - SHOW CONFIGS Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-configs-syntax.md
              - SHOW CREATE SPACE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-space-syntax.md
              - SHOW CREATE TAG EDGE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-tag-edge-syntax.md
              - SHOW HOSTS Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-hosts-syntax.md
              - SHOW INDEXES Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-indexes-syntax.md
              - SHOW PARTS Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-parts-syntax.md
              - SHOW ROLES Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-roles-syntax.md
              - SHOW SNAPSHOTS Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-snapshots-syntax.md
              - SHOW SPACES Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-spaces-syntax.md
              - SHOW TAGS EDGES Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-tags-edges-syntax.md
              - SHOW USERS Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-users-syntax.md

            - DESCRIBE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
            - USE Syntax: manual-EN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
        - Graph Algorithm:
            - FIND PATH Syntax: manual-EN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md

    - Build Develop and Administration:
      - Build:
        - Build Source Code: manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
        - Build by Docker: manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
      - Installation:
        - rpm Installation: manual-EN/3.build-develop-and-administration/2.install/1.install-with-rpm-deb.md
        - Start and Stop Services: manual-EN/3.build-develop-and-administration/2.install/2.start-stop-service.md
      - Configuration:
          - System Requirement: manual-EN/3.build-develop-and-administration/3.configurations/0.system-requirement.md
          - Config Persistency and Priority: manual-EN/3.build-develop-and-administration/3.configurations/1.config-persistency-and-priority.md
          - CONFIG Syntax: manual-EN/3.build-develop-and-administration/3.configurations/2.configs-syntax.md
          - Metad Configuration: manual-EN/3.build-develop-and-administration/3.configurations/3.meta-config.md
          - Graphd Configuration: manual-EN/3.build-develop-and-administration/3.configurations/4.graph-config.md
          - Storaged Configuration: manual-EN/3.build-develop-and-administration/3.configurations/5.storage-config.md
          - Console Configuration: manual-EN/3.build-develop-and-administration/3.configurations/6.console-config.md
      - Account Management Statement:
          - Alter User Syntax: manual-EN/3.build-develop-and-administration/4.account-management-statements/alter-user-syntax.md
          - Built-in Roles: manual-EN/3.build-develop-and-administration/4.account-management-statements/built-in-roles.md
          - Change Password: manual-EN/3.build-develop-and-administration/4.account-management-statements/change-password.md
          - Create User: manual-EN/3.build-develop-and-administration/4.account-management-statements/create-user-syntax.md
          - Drop User: manual-EN/3.build-develop-and-administration/4.account-management-statements/drop-user-syntax.md
          - Grant Role: manual-EN/3.build-develop-and-administration/4.account-management-statements/grant-role-syntax.md
          - Revoke: manual-EN/3.build-develop-and-administration/4.account-management-statements/revoke-syntax.md

      - Batch Data Management:
          - Data Import:
            # - Download And Ingest .sst File: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-import/download-and-ingest-sst-file.md
            - Import .csv File: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-import/import-csv-file.md
            - Spark Writer: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-import/spark-writer.md
          - Data Export:
            - Dump Tool: manual-EN/3.build-develop-and-administration/5.storage-service-administration/data-export/dump-tool.md
          - Storage Balance: manual-EN/3.build-develop-and-administration/5.storage-service-administration/storage-balance.md
          - Cluster Snapshot: manual-EN/3.build-develop-and-administration/5.storage-service-administration/cluster-snapshot.md
          - Long Time-Consuming Task Management: manual-EN/3.build-develop-and-administration/5.storage-service-administration/job-manager.md

      - Monitoring and Statistics:
        - Connect Prometheus: manual-EN/3.build-develop-and-administration/7.minor/0.connect-prometheus.md
        - Metrics: manual-EN/3.build-develop-and-administration/7.minor/1.metrics-exposer.md
        - Meta Metrics: manual-EN/3.build-develop-and-administration/7.minor/2.meta-metrics.md
        - Storage Metrics: manual-EN/3.build-develop-and-administration/7.minor/3.storage-metrics.md
        - Graph Metrics: manual-EN/3.build-develop-and-administration/7.minor/4.graph-metrics.md
      - Development and API:
        - Key Value API: manual-EN/3.build-develop-and-administration/6.develop-and-interface/kv-interfaces.md
        - Nebula Graph Clients: manual-EN/1.overview/2.quick-start/3.supported-clients.md

    - Contributions:
      - Contribute to Documentation: manual-EN/4.contributions/contribute-to-documentation.md
      - cpp Coding Style: manual-EN/4.contributions/cpp-coding-style.md
      - Developer Documentation Style Guide: manual-EN/4.contributions/developer-documentation-style-guide.md
      - How to Contribute: manual-EN/4.contributions/how-to-contribute.md
      - Pull Request and Commit Message Guidelines: manual-EN/4.contributions/pull-request-commit-message-guidelines.md
    - Appendix:
      - Cypher & nGQL: manual-EN/5.appendix/cypher-ngql.md
      - Gremlin & nGQL: manual-EN/5.appendix/gremlin-ngql.md
      - Upgrading Nebula Graph: manual-EN/5.appendix/upgrade-guide.md
    - 中文手册:
      - https://docs.nebula-graph.com.cn/



# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences


# Plugins
plugins:
  - search
  # - mkdocs-versioning:
  #     version: RC4






