name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - v2.6.2

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: apt install
        run: |
          sudo apt update -y
          sudo apt install -y $(cat pkglist.txt)

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r ./requirements.txt

      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com

      - name: Mike Deploy
        run: |
          mike list
          
      - name: Mike Deploy
        run: |
          mike deploy 2.6.2 -p --rebase
          mike set-default 2.6.2 -p --rebase
          mike list

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
      #     publish_dir: ./site
