name: Publish docs via GitHub Pages
on:
  push:
    branches:
    # Remember to add v before the following version number unless the version is master.
      - v3.5.0-sc

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: prepare
        run: sh ./prepare.sh 

      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com
          
      - name: Mike Deploy 3.5.0-sc
        run: |
          # mike delete 3.5.0 -p
          git fetch origin gh-pages --depth=1 # fix mike's CI update
          mike deploy 3.5.0-sc -p --rebase
          mike list
      - name: show git branch
        run: | 
          git branch
          git checkout .
          git checkout gh-pages
      - name: Modify versions.json
        run: | 
          import json
          new_content = {'version': '3.5.0-sc', 'title': '3.5.0-sc', 'aliases': []}
          with open('./versions.json', 'r') as f:
              data = json.load(f)
          for i, item in enumerate(data[:]):
              if item.get('version') == new_content['version'] and item.get('title') == new_content['title']:
                  del data[i]
                  break
          with open('./versions.json', 'w') as outfile:
              json.dump(data, outfile, indent=2)
        shell: python
          
          # not public this branch; but push to web service
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }} 
      #     publish_dir: ./site
