name: Publish docs via GitHub Pages
on:
  push:
    branches:
    # Remember to add v before the following version number unless the version is master.
      - v3.4.3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name : prepare
        run: sh ./prepare.sh 

      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com
          
      - name: Mike Deploy master
        run: |
          # mike delete master -p
          git fetch origin gh-pages --depth=1 # fix mike's CI update
          mike deploy 3.4.3 -p --rebase
          mike list

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
      #     publish_dir: ./site
